### ISSUE TITLE
Allow users to customize the Teams message card

### ISSUE THREAD

**Issue by bzon** [bzon/prometheus-msteams#12]
Using the [Go templating engine](https://golang.org/pkg/text/template/), we can include a feature to let the user create their own YAML templates and feed it to **prometheus-msteams**. The teams message card creation reference is here https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/cards/cards-reference.

We can add a new function named **CreateCardFromTemplates** that will be called if the user use the `--card-template $TEMPLATE_FILE`.

**Comment by bzon** [comment]
@Knappek I haven’t planned on working on this yet. Feel free to play around and see how you can bring this feature to life. Thanks.

**Comment by Knappek** [comment]
Just realized that a message card is not only limited to a size of 14KB but also to a maximum number of 10 sections (see https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/cards/cards-reference#notes-on-the-office-365-connector-card). Hence, we still have a bug that seemed to be fixed #29 . I will address this in the PR for this issue.

**Comment by Knappek** [comment]
@bzon I have created another PR draft: #37. We might need to talk about how to handle too large message cards as I think this might not be possible anymore using this templating approach (see my last commit). 
Therefore, I thought of make it super easy and send out a teams message for each and every prometheus alert.

**Comment by Knappek** [comment]
@bzon is very busy these days, therefor I'd like to have some input from other folks. @LudwigTirazona @shabeermm @daviddob what do you think about sending out a teams message for each and every prometheus alert and don't combine multiple alerts to a single teams message card. Would that be a problem for you?

**Comment by LudwigTirazona** [comment]
It's not too big of an issue for me, but what I foresee is that in some
cases, prometheus-msteams will hit the MS Teams API rate limit.

This will be more avoidable if each message sent to MS Teams has its
maximum allowed size well-utilized, rather than one alert/item sent per
message.

**Comment by Knappek** [comment]
Good point, I didn't know about the MS Teams api rate limit. I agree that it is more appropriate to bundle alerts to single message cards...

Then I'd like to verify my assumptions how to split messages in case that they are too big: Referencing a [detailed example teams message card](https://github.com/bzon/prometheus-msteams/blob/0ac6aa14e0adf2ad9998d182594f56bd5e1be8fc/alert/examples/message_card.json) we need to split the `sections` part as this is the part where we loop over the prometheus alerts as shown in this [example card template](https://github.com/bzon/prometheus-msteams/blob/0ac6aa14e0adf2ad9998d182594f56bd5e1be8fc/default-message-card_old.tmpl#L8-L28), am I right?

**Comment by LudwigTirazona** [comment]
Correct! :)

**Comment by Knappek** [comment]
PR #37 implements the functionality described in this issue. Just a few little things missing (like updating Readme etc.) that I will add in the upcoming days. 
Would be great if some people can already test it and provide some feedback. @sosoriov this might be of interest for you as well.

**Comment by Knappek** [comment]
@cordula-grau fyi, this enhancement solves #27 .

**Comment by Knappek** [comment]
opened PR #37 . Would appreciate some code review, otherwise I'll merge it in the next couple of days and create the minor release 1.1.0.

**Comment by Knappek** [comment]
This feature is now available in v1.1.0 release.
