### ISSUE TITLE
[Proposal] Allow empty connectors in config file

### ISSUE THREAD

**Issue by hiscal2015** [bzon/prometheus-msteams#19]
Hi, 

I tested prometheus-msteams these days, it is really a wonderful tool and better than the one wrote in python introduced in the official link I think.
Now I'm managing connectors with the config file by saltstack, it will dynamically create connectors from pillar values. But if no connectors defined, the service will be failed to start, looks like prometheus-msteams needs at least one connectors to start, so what I have done is this:
```
connectors:
- dummy: "Used for empty connectors"
```
By doing this, if I have no actual connectors defined in my pillar, at least the service can be running.
Any thoughts?

**Comment by bzon** [comment]
@hiscal2015 currently, the server does not support hot reload, "a way of reloading the variables in memory if the config file changes". What you can do is just restart the server when Salt saw a diff and applied the change.
