### ISSUE TITLE
Getting unrecoverable error: unexpected status code 404 from http://promteams:2000/alertmanager

### ISSUE THREAD

**Issue by dibya001** [bzon/prometheus-msteams#21]
Hi I am running prom2teams through docker-compose
my docker-compose.yml file:
 version: '2'
volumes:
    prometheus_data: {}
    grafana_data: {} 
services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports: 
      - "9090:9090"
  alertmanager: 
    image: "prom/alertmanager"
    volumes: 
      - ./msteams.yml:/alertmanager.yml
    command: 
      - "--config.file=/alertmanager.yml"
    ports: 
      - "9093:9093"
  grafana:
    image: grafana/grafana:5.1.0
    depends_on:
     - prometheus
    ports:
      - "3000:3000"
    user: "104"
  promteams:
     image: bzon/prometheus-msteams:latest
     environment:
       - TEAMS_INCOMING_WEBHOOK_URL="https://outlook.office.com/webhook/xxx"
       - PROMTEAMS_DEBUG="true"
     ports:
      - "2000:2000"

alertmanager.yml file
route:
  receiver: receiver
  group_interval: 1m
  repeat_interval: 15m
receivers:
   - name: receiver
     webhook_configs:
     - send_resolved: true
       url: 'http://promteams:2000/alertmanager'
When I do docker-compose up ,Prom2teams container is up and running no issues with that.
But when alertmanager tries to forward notification to it, it shows error code 404

logs:
 alertmanager_1  | level=error ts=2018-08-24T12:31:59.017048267Z caller=notify.go:332 component=dispatcher msg="Error on notify" err="cancelling notify retry for \"webhook\" due to unrecoverable error: unexpected status code 404 from http://promteams:2000/alertmanager"
alertmanager_1  | level=error ts=2018-08-24T12:31:59.017134279Z caller=dispatch.go:280 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="cancelling notify retry for \"webhook\" due to unrecoverable error: unexpected status code 404 from http://promteams:2000/alertmanager"
alertmanager_1  | level=error ts=2018-08-24T12:32:59.017103102Z caller=notify.go:332 component=dispatcher msg="Error on notify" err="cancelling notify retry for \"webhook\" due to unrecoverable error: unexpected status code 404 from http://promteams:2000/alertmanager"
alertmanager_1  | level=error ts=2018-08-24T12:32:59.017262416Z caller=dispatch.go:280 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="cancelling notify retry for \"webhook\" due to unrecoverable error: unexpected status code 404 from http://promteams:2000/alertmanager"

**Comment by bzon** [comment]
Hi @dibya001 it seems like this is the same issue as https://github.com/bzon/prometheus-msteams/issues/20. Can you try adding `TEAMS_REQUEST_URI=alertmanager` in your docker container?

**Comment by bzon** [comment]
@dibya001  please also provide the log of the docker container of prometheus ms teams :)

**Comment by dibya001** [comment]
Hi when I do docker-compose up it is for promteams it is saying
 promteams_1     | 2018/08/24 12:44:10 Adding request uri path //alertmanager
promteams_1     | 2018/08/24 12:44:10 prometheus-msteams server started listening at 0.0.0.0:2000

**Comment by bzon** [comment]
@dibya001 try adding the `TEAMS_REQUEST_URI` this in your docker-compose promteams service: 

```yaml
environment:
- TEAMS_INCOMING_WEBHOOK_URL="https://outlook.office.com/webhook/xxx"
- PROMTEAMS_DEBUG="true"
- TEAMS_REQUEST_URI="alertmanager"
```

**Comment by bzon** [comment]
@dibya001 btw `TEAMS_INCOMING_WEBHOOK_URL` should be your Microsoft Teams Channel webhook..

**Comment by dibya001** [comment]
Still getting the same error
logs:
promteams_1     | 2018/08/24 12:52:00 Adding request uri path /"alertmanager"
promteams_1     | 2018/08/24 12:52:00 prometheus-msteams server started listening at 0.0.0.0:2000
alertmanager_1  | level=debug ts=2018-08-24T12:55:44.017107681Z caller=notify.go:668 component=dispatcher msg="Notify attempt failed" attempt=1 integration=webhook receiver=receiver err="unexpected status code 404 from http://promteams:2000/alertmanager"
alertmanager_1  | level=error ts=2018-08-24T12:55:44.017256284Z caller=notify.go:332 component=dispatcher msg="Error on notify" err="cancelling notify retry for \"webhook\" due to unrecoverable error: unexpected status code 404 from http://promteams:2000/alertmanager"
alertmanager_1  | level=error ts=2018-08-24T12:55:44.017318046Z caller=dispatch.go:280 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="cancelling notify retry for \"webhook\" due to unrecoverable error: unexpected status code 404 from http://promteams:2000/alertmanager"

**Comment by helinyi** [comment]
met the same issue 
level=error ts=2022-05-12T16:24:11.723Z caller=dispatch.go:354 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="prometheus-msteams/webhook[0]: notify retry canceled due to unrecoverable error after 1 attempts: unexpected status code 404: http://prometheus-msteams:2000/teamalert"
