### ISSUE TITLE
Getting status code 500 error while running thorugh docker

### ISSUE THREAD

**Issue by dibya001** [bzon/prometheus-msteams#22]
Alert is being sent to the alert manager. Then it is not able to forward to msteams receiver I guess. I am getting the following error
" unexpected status code 500 from http://teamreceiver:2000/alertmanager"

**Comment by bzon** [comment]
Can you try manually sending an alert to your teamreceiver.

```bash
curl -X POST -d @sample_alert.json http://TEAM_RECEIVER_IP:2000/alertmanager
```

Where `sample_alert.json` is like:

```json
{
    "version": "4",
    "groupKey": "{}:{alertname=\"high_memory_load\"}",
    "status": "firing",
    "receiver": "teams_proxy",
    "groupLabels": {
        "alertname": "high_memory_load"
    },
    "commonLabels": {
        "alertname": "high_memory_load",
        "monitor": "master",
        "severity": "warning"
    },
    "commonAnnotations": {
        "summary": "Server High Memory usage"
    },
    "externalURL": "http://alertmanager:9093",
    "alerts": [
        {
            "labels": {
                "alertname": "high_memory_load",
                "instance": "10.80.40.11:9100",
                "job": "docker_nodes",
                "monitor": "master",
                "severity": "warning"
            },
            "annotations": {
                "description": "xxxxxxx",
                "summary": "Server High Memory usage"
            },
            "startsAt": "2018-03-07T06:33:21.873077559-05:00",
            "endsAt": "0001-01-01T00:00:00Z"
        }
    ]
}```

**Comment by dibya001** [comment]
I will create a file called alert.json?

**Comment by dibya001** [comment]
Yes Now it worked

**Comment by bzon** [comment]
@dibya001  the curl commands works? Maybe you have an communication issue between alert manager and the prometheus-msteams. Please ensure that you can resolve the host `teamreceiver:2000` from your alertmanager host or container (if you are using docker).

**Comment by dibya001** [comment]
Hey I am seeing a weird issue When I curl manually with the ip address, then the prometheus alert manager which is running through docker is able to send an alert . So then when I restart docker-compose, it does not work

**Comment by dibya001** [comment]
When I am giving <servername>:2000/alertmanager inside .yml, it is saying not able to find host. But curl is working

**Comment by dibya001** [comment]
getting this error

 Error: 400 Bad Request
alertmanager_1  | level=debug ts=2018-09-06T13:44:12.769512Z caller=notify.go:668 component=dispatcher msg="Notify attempt failed" attempt=9 integration=webhook receiver=receiver err="unexpected status code 500 from http://teamreceiver:2000/alertmanager"

**Comment by bzon** [comment]
@dibya001 may I see the log of the alertmanager container? I'm suspecting that you may have misconfigured something.

**Comment by bzon** [comment]
@dibya001 feel free to reopen this issue if you still encounter errors. Please provide logs of the prometheus-msteams server/container as requested.
