### ISSUE TITLE
Use proxy

### ISSUE THREAD

**Issue by onedomjohn** [bzon/prometheus-msteams#26]
Thanks for the great app. Just wondered if there was a straightforward way of using it with a proxy server?

Thanks

**Comment by bzon** [comment]
@onedomjohn do you mean running the app directly and not via docker? If yes, you can download the binary for linux and just dot slash it. See releases https://github.com/bzon/prometheus-msteams/releases. 

```
./prometheus-msteams-linux-amd64 server --help
```

**Comment by onedomjohn** [comment]
Thanks for quick reply. I'm actually using it in Kubernetes but I need to forward to the webhook via a proxy. I'm thinking of setting it in the provided Dockerfile but my first test have failed.

**Comment by bzon** [comment]
@onedomjohn ok, so you mean an outbound proxy? Hmm, you can mostly resolve that by adding proxy environment variables (HTTPS_PROXY, HTTP_PROXY, NO_PROXY) in the Deployment. This is a common strategy when running containers in a secured Kubernetes in general.

Currently, the helm chart doesn't support adding extra environments. So you may have to `kubectl edit deploy` your prometheus-msteams.

**Comment by onedomjohn** [comment]
Yeah outbound. That's a good idea though - adding it to the deployment. I'll give that a go now.
