### ISSUE TITLE
Use summary instead of description

### ISSUE THREAD

**Issue by cordula-grau** [bzon/prometheus-msteams#27]
Hi,

as the topic of the alert the summary and not the description should be used, I think.
The description is a more detailed explanation and may be to long for this.

https://github.com/bzon/prometheus-msteams/blob/28af43054976b1c027712ac273f100fa7431cbae/alert/teams.go#L126

Best
C.

**Comment by bzon** [comment]
@cordula-grau at the moment, users are already used to the current formatting so it doesn't make any sense to apply this change now. However, this can be solved in the future when I found a time to work on https://github.com/bzon/prometheus-msteams/issues/12 which lets users use their own template to post to teams channel. :)
