### ISSUE TITLE
repeat_interval: 30s

### ISSUE THREAD

**Issue by buntyray** [bzon/prometheus-msteams#28]
I have enabled a custom webhook with alert manger to self trigger Jenkins jobs when a alert is received. So when I am introducing the Microsoft Team proxy, my original webhook stops working. Basically I get alert via email and on teams that something is wrong but it does not triggers my original webhook to invoke Jenkins to take required action to start my job.

**Comment by bzon** [comment]
@buntyray from what I understand you originally had a Jenkins job that is waiting to be notified by Prometheus alert manager. That Jenkins job is used to send do some operations with whatever data that Prometheus has sent to it.  Sorry, but this is a Prometheus alert manager configuration and has nothing to do with prometheus-msteams.
