### ISSUE TITLE
Alerts sorting is random

### ISSUE THREAD

**Issue by marcinkubica** [bzon/prometheus-msteams#38]
Hi, nice stuff with this app!

Noticed for some reason alert card has keys sorted a bit randomly?

Sometimes Description is at the top, sometimes Summary. Basically every key. 

Cheers

![image](https://user-images.githubusercontent.com/1593987/54743372-da99f080-4bbb-11e9-8b85-62adaf9cc66b.png)

**Comment by Knappek** [comment]
THanks @marcinkubica for reporting that, I haven't recognized it but I was able to reproduce this. I haven't observed it when using the templating approach which will be released in #37 , maybe that fixes it. Let's see...

**Comment by marcinkubica** [comment]
@Knappek  cool stuff!

**Comment by Knappek** [comment]
opened PR #37 . Would appreciate some code review, otherwise I'll merge it in the next couple of days and create the minor release 1.1.0. 
I am pretty sure this will fix your issue @marcinkubica .

**Comment by Knappek** [comment]
created a unit test for that: https://github.com/bzon/prometheus-msteams/pull/37/commits/365431cbcb9f1404dbfa666d1380c35764e7e788

**Comment by marcinkubica** [comment]
@Knappek apologies I had no chance to come back here to retest. Thank you very much for looking at it.
