### ISSUE TITLE
Disable Selected Labels

### ISSUE THREAD

**Issue by varundmishra** [bzon/prometheus-msteams#41]
Is there a way to disable few labels? Currently we get all the labels associated with a particular metric, can this be made more selective?

**Comment by Knappek** [comment]
There is an open PR #37 which enables you to define your teams message card based on a template. With some if else statements you can achieve what you want. I will merge this PR soon in a couple of days. I'd appreciate if you can test this PR beforehand and let me know your feedback :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Knappek** [comment]
Closing issue as it can be handled in #12

**Comment by varundmishra** [comment]
@Knappek : Sure, I would give it a try.
