### ISSUE TITLE
Publish to helm repo?

### ISSUE THREAD

**Issue by bforbis** [bzon/prometheus-msteams#50]
Is it on the roadmap to publish this chart to https://github.com/helm/charts? So far I have been installing my charts using `requirements.yaml`, but there doesn't currently seem to be a way to do that with this repo.

**Comment by Knappek** [comment]
We haven't thought about it yet. Can you briefly explain what you mean with that you install your charts using `requirements.yaml` and what are the advantages of doing so?

**Comment by bforbis** [comment]
You may refer to Helm documentation on this
https://helm.sh/docs/developing_charts/#chart-dependencies

Helm recommendation is to use dynamically linked subchart dependencies if possible through requirements.yaml. It's a little more declarative about what your chart is depending on. This is similar to other package management systems like npm or maven.

Also, it makes this chart a little more discoverable, as it will show up in the helm chart repo browser over at https://hub.helm.sh/

**Comment by Knappek** [comment]
Got it, thanks! Yeah, I think it might be a good idea. Would you like to contribute?

**Comment by code-chris** [comment]
I just published it to my own repo:
https://github.com/code-chris/helm-charts/tree/master/charts/prometheus-msteams

Repo:
https://code-chris.github.io/helm-charts

**Comment by bzon** [comment]
I have published the repo in https://github.com/prometheus-msteams/helm-chart. 

```
helm repo add prometheus-msteams https://prometheus-msteams.github.io/helm-chart/
```
