### ISSUE TITLE
Allow using a configmap to declare connectors

### ISSUE THREAD

**Issue by wy100101** [bzon/prometheus-msteams#51]
I would be nice to be able to declare the connectors in 1 or more configmaps so that connectors could be added separate from the service deployment.

**Comment by Knappek** [comment]
@wy100101 can you briefly explain your use case? I don't understand why you would like to deploy the configuration separately from the app deployment. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Knappek** [comment]
@wy100101 I close this. If you still think this should be tackled, reopen it.
