### ISSUE TITLE
Customise templates

### ISSUE THREAD

**Issue by sosoriov** [bzon/prometheus-msteams#62]
Is it possible to use the AdaptiveCard from Ms to customise the template, I've tried to use it but I always get an error. The predefined actions at this moment is quite limited.

Do you have any example for this?

Thanks in advance

**Comment by AndreyLuchkin** [comment]
As far as I know, currently MS Teams incomming webhook doesn't support AdaptiveCard. So we have to wait until MS will implement it.

**Comment by sosoriov** [comment]
@AndreyLuchkin  thanks for your reply.

mmm at the moment I'm a bit confused. What I want to have is an action button to silence the alerts, It would be great that when you click the button it displays an input box to enter a comment.

As far as I understand that would be possible using AdaptiveCards or am I wrong?

Perhaps do you have an example with something like this.

thanks in advance

**Comment by Knappek** [comment]
Hi @sosoriov , I think what @AndreyLuchkin is trying to say is that Adaptive cards do not support Connectors which is needed to send data to MS Teams via a webhook. 
But maybe you can achieve what you want: In prometheus-msteams, we are using [Office 365 Connector cards](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/cards/cards-reference#office-365-connector-card) which supports [ActionCard actions](https://docs.microsoft.com/en-us/outlook/actionable-messages/message-card-reference#actioncard-action) which support [Inputs](https://docs.microsoft.com/en-us/outlook/actionable-messages/message-card-reference#inputs) where you can use the TextInput.
I haven't tried it out though, but it might be very similar to this [ViewAction](https://github.com/bzon/prometheus-msteams/blob/master/examples/templates/card-with-action.tmpl#L44-L51).
Is this something that might help you? If so, let us know about your findings, a PR would be much appreciated to have some more example templates in the [examples/templates](https://github.com/bzon/prometheus-msteams/tree/master/examples/templates) folder

**Comment by sosoriov** [comment]
Hey guys!

I managed to solve the issue in combination with Alertmanager. So the idea is, you have an action button in msteams which opens the alertmanager UI to create the silence.

Below you will see the code that I used, My apologies in advanced because I'm not a Go developer so It was a bit of try and error.

```
"potentialAction": [
    {
        "@context": "http://schema.org",
        "@type": "ViewAction",
        "name": "Silence Alert",
        {{- range $index, $alert := .Alerts }}
          {{- if eq $index 0}}
            "target": [
                "http://localhost:9093/#/silences/new?filter=%7B{{$c := counter}}{{ range $key, $value := $alert.Labels }}{{if call $c}}%22%2C%20{{ end }}{{ $key }}%3D%22{{ $value }}{{- end }}%22%7D"
            ]
          {{- end }}
        {{- end }}
    }
  ]
```

**Comment by Knappek** [comment]
@sosoriov sounds great. Would you like to create a PR and document it in the examples folder along with a dedicated Readme? I think it is worth for others to know as well. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
