### ISSUE TITLE
Alerts do not work.

### ISSUE THREAD

**Issue by ananthb** [bzon/prometheus-msteams#64]
I've tried POSTing a sample alert with curl and I've tried configuring a route to this instance, but no alerts are fired.

I can see from the server logs, that prometheus-msteams receives the alert, but it fails with this error message:

`failed to template alerts: template: :1:12: executing "" at <{{template "teams.ca...>: template "teams.card" not defined`

I've even copy pasted the default template and tried passing that as a template to the binary with the `--template-file` flag and that didn't work either.

I'm using the latest binary from the release page for linux.

**Comment by ananthb** [comment]
Alerts do work but my yaml file wasn't formatted correctly (doh!). Also it only works if I explicitly pass a template file flag. I feel that this is worth mentioning in the README somewhere.

**Comment by Knappek** [comment]
Actually if you don't pass anything it should pick up the default template. If you run it locally, it only works of you have it running in the repository on the same level as the file location of the default template.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ananthb** [comment]
I downloaded the binary from the releases tab, so I didn't get the template. I moved the template to the same folder as the binary and that worked. Maybe you could add the template to the releases as well? You'd need the binary and at least the default template to get running with this.

**Comment by Knappek** [comment]
here you are...

**Comment by ananthb** [comment]
Thank you!
