### ISSUE TITLE
Use custom message cards with helm chart

### ISSUE THREAD

**Issue by Anjana-dyna** [bzon/prometheus-msteams#70]
When running as a docker container, the custom message card template file is mounted in the container via volume and then the TEMPLATE_FILE environment variable is set.

When running as a binary, the --template-file flag is used.

But there is no mention in the README about how to achieve this when deployed with the helm in a k8s cluster?

In the prometheus-msteams chart, the message card template file is mounted into the container via a configMap volume. This configMap reads data from only the default template `card.tmpl`. 
```
binaryData:
  card.tmpl: {{ .Files.Get "card.tmpl" | b64enc }}
```
The function `.Files.get` reads only those files which are present inside the chart's folder. 

[Here](https://helm.sh/docs/chart_template_guide/#lines) you can read that :

> Currently, there is no way to pass files external to the chart during helm install. So if you are asking users to supply data, it must be loaded using `helm install -f `or `helm install --set`.

So as of now, it is not possible to use an external custom card template file with helm.
According to me, there could be 2 ways to fulfill the requirement:
- Download the chart and manually replace the `prometheus-msteams/card.tmpl` with the custom template file. The custom template file should also have the same name `card.tmpl`. 
-  Provide template file data via values file of the chart. Then allow the configMap to get that data from values file. If the custom template is not specified in the values file, the configMap should use the default template `card.tmpl`.

Am I right here? Is there any other solution for this?

**Comment by Knappek** [comment]
Thank you @Anjana-dyna for filing this issue. Super interesting, I wasn't aware of this limitation in helm, see also [this open PR](https://github.com/helm/helm/issues/3276).
I think you are correct with the above mentioned two workaround solutions. 
For now, we have 2 options:
1. contribute to helm which might take a while to take effect, especially because helm 2 and 3 are diverging, see also [this comment](https://github.com/helm/helm/issues/3276#issuecomment-412942372)
2. simply use your first idea for a workaround which does not require any implementation 
3. follow your second idea: I actually like this idea, we could provide a value in `values.yaml`, e.g. something like `customTemplateB64` which is empty by default. When providing it, we will use this base64 encoded string of a custom template in order to create the configmap. It could be a little bit dirty to provide such a long base64-encoded string to `--set` parameter, or have it in a custom `values.yaml` file, but it kind of gives you the flexibility to use the public prometheus-msteams chart without the need to download the source code.

Looking forward to your contribution :).

**Comment by Knappek** [comment]
The above mentioned "public prometheus-msteams chart" obviously does not yet exist :D...but there is an open issue at least #50 ;)

**Comment by Anjana-dyna** [comment]
> Thank you @Anjana-dyna for filing this issue. Super interesting, I wasn't aware of this limitation in helm, see also [this open PR](https://github.com/helm/helm/issues/3276).
> I think you are correct with the above mentioned two workaround solutions.
> For now, we have 2 options:
> 
> 1. contribute to helm which might take a while to take effect, especially because helm 2 and 3 are diverging, see also [this comment](https://github.com/helm/helm/issues/3276#issuecomment-412942372)
> 2. simply use your first idea for a workaround which does not require any implementation
> 3. follow your second idea: I actually like this idea, we could provide a value in `values.yaml`, e.g. something like `customTemplateB64` which is empty by default. When providing it, we will use this base64 encoded string of a custom template in order to create the configmap. It could be a little bit dirty to provide such a long base64-encoded string to `--set` parameter, or have it in a custom `values.yaml` file, but it kind of gives you the flexibility to use the public prometheus-msteams chart without the need to download the source code.
> 
> Looking forward to your contribution :)

Actually I have a solution as mentioned in the second option. 
We can provide the template file in the values file like:
```
customMessageCardTemplate:
  card.tmpl: |-
    {{ define "teams.card" }}
    .
    .
    .
    .
    {{ end }}
```
But the problem is, the configMap would change to:
```
 ---
apiVersion: v1
kind: ConfigMap
metadata:
 name: prometheus-msteams-card-template
data:
{{- if .Values.customMessageCardTemplate }}
{{ toYaml .Values.customMessageCardTemplate | indent 2 }}
{{- else }}
  card.tmpl: |-
{{ .Files.Get "card.tmpl" | indent 4 }}
{{- end }}
```
That means, configmap would use `data` instead of base64-encoded `binaryData`. 
I was worried if that change in the chart would be suitable for all or not.

Before this, i also tried the same like: 
```
data:
  card.tmpl: |-
{{- if .Values.customMessageCardTemplate }}
{{ toYaml .Values.customMessageCardTemplate | indent 4 }}
{{- else }}
{{ .Files.Get "card.tmpl" | indent 4 }}
{{- end }}
```
In this case, we can use the helm install command to set the value of customMessageCardTemplate by loading the template file itself. For example, If the `custom-card.tmpl` file contains the template data, the install command would be like:
`helm install --name prometheus-msteams --set-file customMessageCardTemplate=custom-card.tmpl --dry-run --debug ./prometheus-msteams`

But I got resulting configmap like. When reading the value from a file, It contains some extra characters also. That doesn't looks fine.
```
apiVersion: v1
kind: ConfigMap
metadata:
 name: prometheus-msteams-card-template
data:
  card.tmpl: |-
    "{{ define \"teams.card\" }}\r\n{\r\n  \"@type\": \"MessageCard\",\r\n  \"@context\":
      \"http://schema.org/extensions\",\r\n  \"themeColor\": \"{{- if eq .Status \"resolved\"
      -}}2DC72D\r\n                 {{- else if eq .Status \"firing\" -}}\r\n                    {{-
      if eq .CommonLabels.severity \"critical\" -}}8C1A1A\r\n                    {{- else
      if eq .CommonLabels.severity \"warning\" -}}FFA500\r\n                    {{- else
      -}}808080{{- end -}}\r\n                 {{- else -}}808080{{- end -}}\",\r\n  \"summary\":
      \"{{- if eq .CommonAnnotations.summary \"\" -}}\r\n                  {{- if eq .CommonAnnotations.message
      \"\" -}}\r\n                    {{- .CommonLabels.cluster -}}-cluster\r\n                  {{-
      else -}}\r\n                    {{- .CommonAnnotations.message -}}\r\n                  {{-
      end -}}\r\n              {{- else -}}\r\n                  {{- .CommonAnnotations.summary
      -}}\r\n              {{- end -}}\",\r\n  \"title\": \"Prometheus Alert ({{ .Status
      }})\",\r\n  \"sections\": [ {{$externalUrl := .ExternalURL}}\r\n  {{- range $index,
      $alert := .Alerts }}{{- if $index }},{{- end }}\r\n    {\r\n      \"activityTitle\":
      \"[{{ $alert.Annotations.description }}]({{ $externalUrl }})\",\r\n      \"facts\":
      [\r\n        {{- range $key, $value := $alert.Annotations }}\r\n        {\r\n          \"name\":
      \"{{ reReplaceAll \"_\" \" \" $key }}\",\r\n          \"value\": \"{{ reReplaceAll
      \"_\" \" \" $value }}\"\r\n        },\r\n        {{- end -}}\r\n        {{$c :=
      counter}}{{ range $key, $value := $alert.Labels }}{{if call $c}},{{ end }}\r\n        {\r\n
      \         \"name\": \"{{ reReplaceAll \"_\" \" \" $key }}\",\r\n          \"value\":
      \"{{ reReplaceAll \"_\" \" \" $value }}\"\r\n        }\r\n        {{- end }}\r\n
      \     ],\r\n      \"markdown\": true\r\n    }\r\n    {{- end }}\r\n  ]\r\n}\r\n{{
      end }}\r\n"
```

I thought if this method worked correctly, and took the same data to configMap, then I can try with base-64 encoded data also. In that case, we can maintain `binaryData` itself. But unfortunately, that didn't happen. That's why I needed to switch from `binaryData` to `data`.

Please feel free to tell me if you have any suggestions.

**Comment by Knappek** [comment]
Thanks @Anjana-dyna. Closing this in regards to #71 .
