### ISSUE TITLE
Config.yml webhook secrets leaked on INFO log level

### ISSUE THREAD

**Issue by leojonathanoh** [bzon/prometheus-msteams#74]
Since [`v1.0` ](https://github.com/bzon/prometheus-msteams/blame/66869dfe1b35feddf3e217d2b42f21dba40a09cd/cmd/server.go#L220), the webhooks specified in `config.yml` are spit out in the container logs on the `INFO` log level. 

As with best practices, these secrets should either be logged on only the `DEBUG` log level, or they could be logged on the `INFO` level but at least be redacted. This is prevent secrets from being leaked as plaintext onto the disk or to the backing log database.

**Comment by Knappek** [comment]
Thanks @leojonathanoh for the heads up. I think it is not a good idea to expose any kind of secrets at all, in general. So I removed it in #76 . Would be great if you can review.

**Comment by leojonathanoh** [comment]
would it be better if #76 was split up into two PRs, one addressing this issue and the other addressing #73?

I'd consider a fix for this to be a bugfix, whereas a fix for #73 I'd consider to be breaking for some users who have been reliant or expect some kind of verbose logging. I'm not familiar enough with the release cycle, so I'll leave it to you guys to decide whether to split the PR up :)

**Comment by Knappek** [comment]
I don't think not printing secrets is a breaking major change. I would just go ahead and put it in a patch version upgrade. @bzon any concerns?

**Comment by Knappek** [comment]
addressed in #76
